name: codalab-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - cpuonly
  # - pytorch-cuda=12.4  # requires NVIDIA driver >= 550
  # - cudnn
  - numpy
  - pandas
  - scikit-learn
  - mne
  - pip:
      - eegdash
      - braindecode
      - lightning
