name: codalab-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - cudnn
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - notebook
  - seaborn
  - scipy
  - mne

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.9.0
      - torchvision
      - torchaudio 

      - tensorboard
  
      - eegdash
      - braindecode
      - lightning
      - mamba-ssm

      
